# Generated by Django 6.0.5 on 2026-06-26 03:06

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def assign_existing_rows_to_default_store(apps, schema_editor):
    Store = apps.get_model('api', 'Store')
    store, _ = Store.objects.get_or_create(
        id='default-store',
        defaults={'store_name': "King's Store", 'subscription_plan': 'FREE'},
    )
    for model_name in [
        'User',
        'Category',
        'Customer',
        'CustomerRequest',
        'Debt',
        'Delivery',
        'Expense',
        'InventoryLog',
        'Notification',
        'Payment',
        'Product',
        'Report',
        'Sale',
        'SaleItem',
        'Supplier',
    ]:
        model = apps.get_model('api', model_name)
        model.objects.filter(store__isnull=True).update(store=store)
    User = apps.get_model('api', 'User')
    User.objects.filter(store=store, role='ADMIN').update(role='OWNER')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_import_pelumi_wipes_diapers_soap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(default=api.models.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('store_name', models.CharField(db_column='storeName', max_length=255)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], db_column='subscriptionPlan', default='FREE', max_length=20)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Store',
                'ordering': ['store_name'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_code',
            field=models.CharField(blank=True, db_column='serialCode', max_length=255, null=True, verbose_name='barcode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(db_column='invoiceNo', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('SALES_STAFF', 'Sales Staff'), ('INVENTORY_STAFF', 'Inventory Staff'), ('STAFF', 'Staff'), ('ACCOUNTANT', 'Accountant'), ('WAREHOUSE', 'Warehouse')], default='STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.store'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.store'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to='api.store'),
        ),
        migrations.AddField(
            model_name='debt',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='api.store'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.store'),
        ),
        migrations.AddField(
            model_name='expense',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.store'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='api.store'),
        ),
        migrations.AddField(
            model_name='notification',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.store'),
        ),
        migrations.AddField(
            model_name='payment',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.store'),
        ),
        migrations.AddField(
            model_name='report',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.store'),
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.store'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='api.store'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='api.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, db_column='storeId', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.store'),
        ),
        migrations.RunPython(assign_existing_rows_to_default_store, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['store'], name='category_store_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['store'], name='customer_store_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['store'], name='request_store_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['store'], name='debt_store_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['store'], name='delivery_store_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['store'], name='expense_store_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['store'], name='inventory_store_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['store'], name='notification_store_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['store'], name='payment_store_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store'], name='product_store_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['store'], name='report_store_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store'], name='sale_store_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['store'], name='saleitem_store_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['store'], name='supplier_store_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='category_store_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'sku'), name='product_store_sku_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'serial_code'), name='product_store_barcode_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('store', 'invoice_no'), name='sale_store_invoice_uniq'),
        ),
    ]
