export const PRODUCT_CATEGORIES = [
  "DEFAULT",
  "Accessories",
  "Air Freshener",
  "Bar Soap",
  "Body Oil",
  "Body Scrub",
  "Body Wash / Gel",
  "Body cream",
  "CLEANSING",
  "Cleansers & Toners",
  "Creams",
  "Creams cream",
  "Cup Creams",
  "Cup Soap",
  "DIAPERS",
  "Detergent",
  "Face Cream",
  "Face Creams",
  "Face Mask",
  "Face cream",
  "Flirt",
  "Hair Care",
  "Hair Cream / Treatment",
  "Hair Treatment",
  "Hair cream",
  "Insecticide",
  "LOTION",
  "Lip Gloss",
  "Liquid Baby Wash",
  "Liquid Washes",
  "Lotion",
  "Lotion Creams",
  "Lotions",
  "Makeup",
  "Nail Polish",
  "Oil",
  "Perfume",
  "Perfume / Spray",
  "Perfumes",
  "Polish",
  "Powder",
  "Roll On",
  "SALTS",
  "SOAP",
  "Scrub",
  "Skin Care",
  "Toiletries",
  "Tubes",
  "Tubes Tubes",
  "WIPES / PAD",
  "accessories",
  "bsc",
  "cleansing",
  "computer",
  "hair Cream",
  "logo",
  "lotion",
  "mackup",
  "oil",
  "ori",
  "pad",
  "powder",
  "serum spray",
  "toiletriess",
  "tube",
  "alchohl drink",
  "soft drink"
] as const;
